# Generated by Django 4.2.6 on 2023-11-09 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_order_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='staff',
        ),
    ]
