# Generated by Django 5.0 on 2024-01-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_remove_product_category_remove_product_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.PositiveBigIntegerField(editable=False, null=True),
        ),
    ]
