# Generated by Django 5.0 on 2024-01-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_sale_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
