# Generated by Django 5.0 on 2024-01-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_sale_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sub_total',
            field=models.PositiveBigIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
    ]
