# Generated by Django 5.0 on 2024-01-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_sale_sub_total_alter_sale_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
